Microsoft Windows [Version 10.0.26100.3194]
(c) Microsoft Corporation. All rights reserved.

C:\Users\gboye>az cognitiveservices account  show \ --name MyAITextAnalytics \ --resource-group MyAIResourceGroup \ --query "properties.endpoint"
unrecognized arguments: \ \ \

Examples from AI knowledge base:
https://aka.ms/cli_ref
Read more about the command in reference docs

C:\Users\gboye>az --version
azure-cli                         2.69.0

core                              2.69.0
telemetry                          1.1.0

Dependencies:
msal                            1.31.2b1
azure-mgmt-resource               23.1.1

Python location 'C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe'
Config directory 'C:\Users\gboye\.azure'
Extensions directory 'C:\Users\gboye\.azure\cliextensions'

Python (Windows) 3.12.8 (tags/v3.12.8:2dc476b, Dec  3 2024, 19:30:04) [MSC v.1942 64 bit (AMD64)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.

C:\Users\gboye>az login
Select the account you want to log in with. For more information on login with Azure CLI, see https://go.microsoft.com/fwlink/?linkid=2271136

Retrieving tenants and subscriptions for the selection...

[Tenant and subscription selection]

No     Subscription name     Subscription ID                       Tenant
-----  --------------------  ------------------------------------  -----------------
[1] *  Azure subscription 1  b7a9fd32-5d04-489d-88a4-e613c8d87aa9  Default Directory

The default is marked with an *; the default tenant is 'Default Directory' and subscription is 'Azure subscription 1' (b7a9fd32-5d04-489d-88a4-e613c8d87aa9).

Select a subscription and tenant (Type a number or Enter for no changes):

Tenant: Default Directory
Subscription: Azure subscription 1 (b7a9fd32-5d04-489d-88a4-e613c8d87aa9)

[Announcements]
With the new Azure CLI login experience, you can select the subscription you want to use more easily. Learn more about it and its configuration at https://go.microsoft.com/fwlink/?linkid=2271236

If you encounter any problem, please open an issue at https://aka.ms/azclibug

[Warning] The login output has been updated. Please be aware that it no longer displays the full list of available subscriptions by default.


C:\Users\gboye>az group create --name MAIResourceGroup --location uksouth
{
  "id": "/subscriptions/b7a9fd32-5d04-489d-88a4-e613c8d87aa9/resourceGroups/MAIResourceGroup",
  "location": "uksouth",
  "managedBy": null,
  "name": "MAIResourceGroup",
  "properties": {
    "provisioningState": "Succeeded"
  },
  "tags": null,
  "type": "Microsoft.Resources/resourceGroups"
}

C:\Users\gboye>az cognitiveservices account create \ --name MyAITextAnalytics \ --resource-g
roup MyAIResourceGroup \ --kind TextAnalytics \ sku F0 \ --location uksouth --yes
the following arguments are required: --sku/--sku-name

Examples from AI knowledge base:
az cognitiveservices account create --name myresource --resource-group myResourceGroup --kind Face --sku S0 --location WestEurope --yes
Create an S0 face API Cognitive Services account in West Europe without confirmation required.

az cognitiveservices account create --kind Face --location WestEurope --name myresource --resource-group myResourceGroup --sku S0 --subscription MySubscription --yes
Manage Azure Cognitive Services accounts. (autogenerated)

https://docs.microsoft.com/en-US/cli/azure/cognitiveservices/account#az_cognitiveservices_account_create
Read more about the command in reference docs

C:\Users\gboye>az cognitive services account create \ --name MyAITextAnalytics \ --resource-
group MyAIResourceGroup \ --kind TextAnalytics \ --sku F0 \ --location uksouth \ --yes
'cognitive' is misspelled or not recognized by the system.

Examples from AI knowledge base:
https://aka.ms/cli_ref
Read more about the command in reference docs

C:\Users\gboye>az cognitive services account create \ --name MyAITextAnalytics \ --resource-

'cognitive' is misspelled or not recognized by the system.

Examples from AI knowledge base:
https://aka.ms/cli_ref
Read more about the command in reference docs

C:\Users\gboye>group MyAIResourceGroup \ --kind TextAnalytics \ --sku F0 \ --location uksouth \ --yes
'group' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\gboye>group MyAIResourceGroup \ --kind TextAnalytics \ --sku F0 \ --location uksouth \ --yes
'group' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\gboye>az cognitive services account create \ --name MyAITextAnalytics \ --resource-

'cognitive' is misspelled or not recognized by the system.

Examples from AI knowledge base:
https://aka.ms/cli_ref
Read more about the command in reference docs

C:\Users\gboye>group MyAIResourceGroup \ --kind TextAnalytics \ --sku F0 \ --location uksouth \ --yes
'group' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\gboye>az cognitiveservices account create \ --name MyAITextAnalytics \ --resource-group MyAIResourceGroup \ --kind TextAnalytics \ --sku F0 \ --location uksouth \ --yes
unrecognized arguments: \ \ \ \ \ \

Examples from AI knowledge base:
az cognitiveservices account create --name myresource --resource-group myResourceGroup --kind Face --sku S0 --location WestEurope --yes
Create an S0 face API Cognitive Services account in West Europe without confirmation required.

az cognitiveservices account create --kind Face --location WestEurope --name myresource --resource-group myResourceGroup --sku S0 --subscription MySubscription --yes
Manage Azure Cognitive Services accounts. (autogenerated)

https://docs.microsoft.com/en-US/cli/azure/cognitiveservices/account#az_cognitiveservices_account_create
Read more about the command in reference docs

C:\Users\gboye>az group show --name MyAIResourceGroup
{
  "id": "/subscriptions/b7a9fd32-5d04-489d-88a4-e613c8d87aa9/resourceGroups/MyAIResourceGroup",
  "location": "uksouth",
  "managedBy": null,
  "name": "MyAIResourceGroup",
  "properties": {
    "provisioningState": "Succeeded"
  },
  "tags": null,
  "type": "Microsoft.Resources/resourceGroups"
}

C:\Users\gboye>az cognitiveservices account show --name MyAITextAnalytics --resource-group M
yAIResourceGroup
{
  "etag": "\"3a05f225-0000-1100-0000-67b598540000\"",
  "id": "/subscriptions/b7a9fd32-5d04-489d-88a4-e613c8d87aa9/resourceGroups/MyAIResourceGroup/providers/Microsoft.CognitiveServices/accounts/MYAITextAnalytics",
  "identity": null,
  "kind": "TextAnalytics",
  "location": "uksouth",
  "name": "MYAITextAnalytics",
  "properties": {
    "abusePenalty": null,
    "allowedFqdnList": null,
    "apiProperties": {
      "aadClientId": null,
      "aadTenantId": null,
      "additionalProperties": null,
      "eventHubConnectionString": null,
      "qnaAzureSearchEndpointId": null,
      "qnaAzureSearchEndpointKey": null,
      "qnaRuntimeEndpoint": null,
      "statisticsEnabled": null,
      "storageAccountConnectionString": null,
      "superUser": null,
      "websiteName": null
    },
    "callRateLimit": null,
    "capabilities": [
      {
        "name": "VirtualNetworks",
        "value": null
      },
      {
        "name": "CustomerManagedKey",
        "value": null
      },
      {
        "name": "CustomerManagedStorage",
        "value": null
      },
      {
        "name": "Cloud",
        "value": "TextAnalytics.Healthcare,TextAnalytics.Analyze,QuestionAnswer.AllApis,LanguageService.QuestionAnsweringApis"
      },
      {
        "name": "Container",
        "value": "TextAnalytics.Healthcare,TextAnalytics.EntityV3,TextAnalytics.EntityONNX,TextAnalytics.Keyphrase,TextAnalytics.KeyphraseV2,TextAnalytics.KeyPhraseONNX,TextAnalytics.LanguageFastText,TextAnalytics.Language,TextAnalytics.LanguageV2,TextAnalytics.Sentiment,TextAnalytics.SentimentV2,TextAnalytics.SentimentV3,TextAnalytics.SentimentV3Preview,TextAnalytics.SentimentONNX,TextAnalytics.CustomNER,TextAnalytics.textanalyticsdispatcher,TextAnalytics.SummarizationFrontend,TextAnalytics.SummarizationWorker,TextAnalytics.PII,TextAnalytics.CluRuntime,TextAnalytics.NER"
      }
    ],
    "commitmentPlanAssociations": null,
    "customSubDomainName": null,
    "dateCreated": "2025-02-19T08:37:08.3437264Z",
    "deletionDate": null,
    "disableLocalAuth": null,
    "dynamicThrottlingEnabled": null,
    "encryption": null,
    "endpoint": "https://uksouth.api.cognitive.microsoft.com/",
    "endpoints": {
      "Container": "https://uksouth.api.cognitive.microsoft.com/",
      "Conversational Language Understanding Authoring": "https://uksouth.api.cognitive.microsoft.com/",
      "ConversationalLURuntime": "https://uksouth.api.cognitive.microsoft.com/",
      "Custom Question Answering": "https://uksouth.api.cognitive.microsoft.com/",
      "Custom Question Answering Authoring": "https://uksouth.api.cognitive.microsoft.com/",
      "Custom Text Authoring": "https://uksouth.api.cognitive.microsoft.com/",
      "LUIS": "https://uksouth.api.cognitive.microsoft.com/",
      "Language": "https://uksouth.api.cognitive.microsoft.com/",
      "QnAMaker": "https://uksouth.api.cognitive.microsoft.com/",
      "QuestionAnswering": "https://uksouth.api.cognitive.microsoft.com/",
      "Text Analytics": "https://uksouth.api.cognitive.microsoft.com/",
      "Turing": "https://uksouth.api.cognitive.microsoft.com/"
    },
    "internalId": "e82d4ac7841f47dfbe6220994891606f",
    "isMigrated": false,
    "locations": null,
    "migrationToken": null,
    "networkAcls": null,
    "privateEndpointConnections": [],
    "provisioningState": "Succeeded",
    "publicNetworkAccess": "Enabled",
    "quotaLimit": {
      "count": null,
      "renewalPeriod": null,
      "rules": [
        {
          "count": 5000.0,
          "dynamicThrottlingEnabled": null,
          "key": "workflow.endpoint.postcalls",
          "matchPatterns": [
            {
              "method": "*",
              "path": "/language/:analyze-conversations"
            }
          ],
          "minCount": null,
          "renewalPeriod": 2592000.0
        }
      ]
    },
    "restore": null,
    "restrictOutboundNetworkAccess": null,
    "scheduledPurgeDate": null,
    "skuChangeInfo": null,
    "userOwnedStorage": null
  },
  "resourceGroup": "MyAIResourceGroup",
  "sku": {
    "capacity": null,
    "family": null,
    "name": "F0",
    "size": null,
    "tier": null
  },
  "systemData": {
    "createdAt": "2025-02-19T08:37:08.155592+00:00",
    "createdBy": "gboyega.micro@gmail.com",
    "createdByType": "User",
    "lastModifiedAt": "2025-02-19T08:37:08.155592+00:00",
    "lastModifiedBy": "gboyega.micro@gmail.com",
    "lastModifiedByType": "User"
  },
  "tags": null,
  "type": "Microsoft.CognitiveServices/accounts"
}

C:\Users\gboye>az cognitiveservices account keys list --name MyAITextAnalytics --resource-gr
oup MyAIResourceGroup
{
  "key1": "f080d9916d47428087d5a918453a4917",
  "key2": "74f004aaf6524a369b3d670eed3ba57e"
}

C:\Users\gboye>nano ~/.bashrc
'nano' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\gboye>echo %COGNITIVE_API_KEY%
%COGNITIVE_API_KEY%

C:\Users\gboye>echo %COGNITIVE_API_KEY%
%COGNITIVE_API_KEY%

C:\Users\gboye>az cognitiveservices account show --name MyAITextAnalytics --resource-group MyAIResourceGroup --query "properties.endpoint"
"https://uksouth.api.cognitive.microsoft.com/"

C:\Users\gboye>az cognitiveservices account show --name MyAITextAnalytics --resource-group MyAIResourceGroup --query "properties.endpoint"
"https://uksouth.api.cognitive.microsoft.com/"

C:\Users\gboye>
C:\Users\gboye>az cognitiveservices account show --name MyAITextAnalytics --resource-group MyAIResourceGroup --query "properties.endpoint"
"https://uksouth.api.cognitive.microsoft.com/"

C:\Users\gboye>